name: Build and Test Pipeline

on:
  push:
    paths-ignore:
      - '*.md'
      - '.github/**/*.yml'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Verify
        run: mvn -e -B verify